In [1]:
import pandas as pd
df=pd.read_csv(r"E:\Github Projects\Otodom\Otodom.csv")
df.head()

,posting_id,timestamp,year,month,weekday,price,location,no_of_rooms,is_for_sale,title,market,form_of_property,surface,remote_support,advertiser_type,url,description
0,4n5Li,20-02-2024,2024,2,Tuesday,660000.0,"Mysiadło, Lesznowola, piaseczyński, mazowieckie",2,True,Kameralny zakątek blisko wszędzie 2 pokoje 55 ...,secondary,pełna własność,55.00,False,agency,https://otodom.pl/pl/oferta/kameralny-zakatek-...,Jeśli chcesz mieszkać w zielonej okolicy lecz ...
1,4p7BD,20-02-2024,2024,2,Tuesday,395000.0,"ul. Saperów 12, Kazuń Nowy, Czosnów, nowodwors...",2,True,"Wykończone mieszkanie, gotowe do zamieszkania!",secondary,pełna własność,33.72,False,agency,https://otodom.pl/pl/oferta/wykonczone-mieszka...,Z dumą prezentujemy na sprzedaż urokliwe miesz...
2,4paZL,20-02-2024,2024,2,Tuesday,330000.0,"ul. Reinholda Barcza, Szczytno, szczycieński, ...",4,True,"Mieszkanie 4-pokojowe,blisko jeziora na I pięt...",secondary,pełna własność,56.51,False,agency,https://otodom.pl/pl/oferta/mieszkanie-4-pokoj...,"Jeśli szukają Państwo idealnej nieruchomości, ..."
3,4oQHS,20-02-2024,2024,2,Tuesday,688000.0,"ul. Niepodległości, Gorzów Wielkopolski, lubuskie",4,True,"4 pokoje, 81 m2, w super lokalizacji",secondary,pełna własność,81.00,False,private,https://otodom.pl/pl/oferta/4-pokoje-81-m2-w-s...,"Sprzedaż bez pośredników, bez prowizjiSprzedam..."
4,4oYh5,20-02-2024,2024,2,Tuesday,390000.0,"ul. Kwiatowa, Lubin, lubiński, dolnośląskie",2,True,Sprzedam Mieszkanie ul. Kwiatowa-Lubin,primary,pełna własność,40.18,False,private,https://otodom.pl/pl/oferta/sprzedam-mieszkani...,Oferta od właściciela- bez Pośredników.\r\n\r\...

In [7]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse=False) # Encoding categorical columns to numerical values
encoded = encoder.fit_transform(df[['remote_support', 'is_for_sale']])

df_encoded = pd.DataFrame(encoded, columns=encoder.get_feature_names_out(['remote_support', 'is_for_sale']))
df_encoded

C:\Users\ASUS\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

     remote_support_False  remote_support_True  is_for_sale_True
0                     1.0                  0.0               1.0
1                     1.0                  0.0               1.0
2                     1.0                  0.0               1.0
3                     1.0                  0.0               1.0
4                     1.0                  0.0               1.0
..                    ...                  ...               ...
968                   1.0                  0.0               1.0
969                   0.0                  1.0               1.0
970                   1.0                  0.0               1.0
971                   1.0                  0.0               1.0
972                   1.0                  0.0               1.0

[973 rows x 3 columns]

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

X = df.drop(columns=['price']) # Features and Target
y = df['price']

numeric_features = ['surface', 'no_of_rooms'] # Preprocessing for numerical features
numeric_transformer = StandardScaler()

categorical_features = ['market', 'advertiser_type', 'remote_support']  # Preprocessing for categorical features
categorical_transformer = OneHotEncoder()

preprocessor = ColumnTransformer(
    transformers=[ # Bundle preprocessing for numerical and categorical data
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)])

model = Pipeline(steps=[('preprocessor', preprocessor), # Preprocessing and modeling pipeline
                        ('classifier', LinearRegression())])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0) #Split data into train and test sets

model.fit(X_train, y_train)# Fit the model

y_pred = model.predict(X_test)# Predict and evaluate the model
mse = mean_squared_error(y_test, y_pred)
rmse = mse**0.5

print(f'Root Mean Squared Error: {rmse}')

Root Mean Squared Error: 400071.11258627556

In [14]:
X = df.drop(columns=['price', 'posting_id'])  # Exclude posting_id from features

In [15]:
df = df.drop(columns='posting_id')

In [16]:
# Using ColumnTransformer to selectively apply transformations
from sklearn.compose import ColumnTransformer

numeric_features = ['surface', 'no_of_rooms']  # Numeric Features
categorical_features = ['market', 'advertiser_type']  # Categorical Features

preprocessor = ColumnTransformer(
    transformers = [
        ('num', StandardScaler(), numeric_features),
        ('cat', OneHotEncoder(), categorical_features)],
    remainder='passthrough') # This ensures 'posting_id' is passed through unmodified

In [17]:
print(df.dtypes)
print(df.head())

timestamp            object
year                  int64
month                 int64
weekday              object
price               float64
location             object
no_of_rooms           int64
is_for_sale            bool
title                object
market               object
form_of_property     object
surface             float64
remote_support         bool
advertiser_type      object
url                  object
description          object
dtype: object
    timestamp  year  month  weekday     price  \
0  20-02-2024  2024      2  Tuesday  660000.0
1  20-02-2024  2024      2  Tuesday  395000.0
2  20-02-2024  2024      2  Tuesday  330000.0
3  20-02-2024  2024      2  Tuesday  688000.0
4  20-02-2024  2024      2  Tuesday  390000.0

                                            location  no_of_rooms  \
0    Mysiadło, Lesznowola, piaseczyński, mazowieckie            2
1  ul. Saperów 12, Kazuń Nowy, Czosnów, nowodwors...            2
2  ul. Reinholda Barcza, Szczytno, szczycieński, ...            4
3  ul. Niepodległości, Gorzów Wielkopolski, lubuskie            4
4        ul. Kwiatowa, Lubin, lubiński, dolnośląskie            2

   is_for_sale                                              title     market  \
0         True  Kameralny zakątek blisko wszędzie 2 pokoje 55 ...  secondary
1         True     Wykończone mieszkanie, gotowe do zamieszkania!  secondary
2         True  Mieszkanie 4-pokojowe,blisko jeziora na I pięt...  secondary
3         True               4 pokoje, 81 m2, w super lokalizacji  secondary
4         True             Sprzedam Mieszkanie ul. Kwiatowa-Lubin    primary

  form_of_property  surface  remote_support advertiser_type  \
0   pełna własność    55.00           False          agency
1   pełna własność    33.72           False          agency
2   pełna własność    56.51           False          agency
3   pełna własność    81.00           False         private
4   pełna własność    40.18           False         private

                                                 url  \
0  https://otodom.pl/pl/oferta/kameralny-zakatek-...
1  https://otodom.pl/pl/oferta/wykonczone-mieszka...
2  https://otodom.pl/pl/oferta/mieszkanie-4-pokoj...
3  https://otodom.pl/pl/oferta/4-pokoje-81-m2-w-s...
4  https://otodom.pl/pl/oferta/sprzedam-mieszkani...

                                         description
0  Jeśli chcesz mieszkać w zielonej okolicy lecz ...
1  Z dumą prezentujemy na sprzedaż urokliwe miesz...
2  Jeśli szukają Państwo idealnej nieruchomości, ...
3  Sprzedaż bez pośredników, bez prowizjiSprzedam...
4  Oferta od właściciela- bez Pośredników.\r\n\r\...

In [20]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

numeric_features = ['surface', 'no_of_rooms']# Features to use for prediction
categorical_features = ['market', 'advertiser_type']

preprocessor = ColumnTransformer( # Preprocessor
    transformers=[
        ('num', StandardScaler(), numeric_features),
        ('cat', OneHotEncoder(), categorical_features)
    ])

model = LinearRegression()

pipeline = Pipeline(steps=[('preprocessor', preprocessor), ('model', model)]) # Pipeline creation

X = df[numeric_features + categorical_features] # Define features and target variable
y = df['price']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) # Split the data

pipeline.fit(X_train, y_train) # Model Training

y_pred = pipeline.predict(X_test) # Predictions

mse = mean_squared_error(y_test, y_pred)
rmse = mse**0.5

print(f'Root Mean Squared Error: {rmse}')

Root Mean Squared Error: 330905.5321845191